### ISSUE TITLE
Error using /dev/ttyUSB0

### ISSUE THREAD

**Issue by briancday** [BobRak/OpenHAB-cm11a#5]
I suspect this problem is "user error", but I thought it might be helpful to pass along my experience.  I'm having an issue where the binding will not connect to the USB serial adapter on /dev/ttyUSB0.

Situation:
----------
- Running Openhab2 on headless Ubuntu 14
- Plugged CM11a into USB port via serial to USB adapter
- Verified was working by running heyu (this may be the problem... that I'm still running heyu)
- Moved latest jar (plus org.openhab.io.transport.serial.jar ) into /usr/share/openhab2/addons
- Configured simple cm11a.things, and cm11a.items files under /etc/openhab2/things following examples.
- reboot server for safe measure

Expected Result:
-----------------
- Open PaperUI 
   -- see the CM11a binder is connected
   -- see things
   -- turn things on/off, and they work

Actual Result:
--------------
- Open PaperUI
   -- see the CM11a binder is NOT connected
   -- see things
   -- turn things on/off, and they do NOT work

Error Messages via UI
--------------
CM11a Binding for X10 devices OFFLINE
CM11a Binding for X10 devices
cm11a:cm11a:MyCm11a
Status: OFFLINE - COMMUNICATION_ERROR No such port exists on this machine: /dev/ttyUSB0

Error Messages in the Log
--------------
2017-01-19 13:23:22.298 [hingStatusInfoChangedEvent] - 'cm11a:cm11a:e975db78' changed from OFFLINE (COMMUNICATION_ERROR): No such port exists on this machine: /dev/ttyUSB0 to REMOVING

*** However, the port is there, and the user has access to the dialout group:
crw-rw---- 1 root dialout 188, 0 Jan 19 13:19 /dev/ttyUSB0
openhab : openhab tty dialout

**Comment by BobRak** [comment]
Brian:

Sorry to be slow in responding. I am away from home and this is the first
chance I've had to respond. Plus I only have a small Chromebook with me.


   - Is the hardware a Raspberry Pi?
   - Is /dev/ttyUSB0 the same port you use with heyu?
   - I have heyu on one Pi and OpenHAB on another so I haven't tried
   running them on the same computer. For sure heyu should not be running.
   Also, it spawns daemon so make sure it has't been started since a reboot.
   - Somehow it sticks in my mind that maybe the port name is different but
   I'm not sure.

I'll be home Monday and can try to look further at my own installation
then. Let me know if you make any progress.

Thanks,

Bob

**Comment by briancday** [comment]
I’m running this on an Ubuntu VM under ESXi.  I suspect that heyu conflicts for the usb port.  I’ll uninstall and try again.

B

**Comment by briancday** [comment]
Bob:

 

I turned off the heyu daemon and restarted openhab2 and it is now working.  

Lesson: Don’t run heyu and openhab2 (with cm11a binding) on the same machine fighting for the same CM11a.

---

Brian
